### ISSUE TITLE
选择安装位置时一处乱码

### ISSUE THREAD

**Issue by SnowMoonSS** [ottercorp/FFXIVQuickLauncher#11]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

安装启动器时有一处乱码
![image](https://user-images.githubusercontent.com/21017431/170884505-694f9a8b-b214-4380-94d4-476949745ca7.png)

### 平台

Windows

**Comment by Loskh** [comment]
是否开启了“使用 Unicode UTF-8 提供全球语言支持”？

**Comment by SnowMoonSS** [comment]
![image](https://user-images.githubusercontent.com/21017431/170947765-5c9aecbe-6d87-47d1-b8da-f60f31fa04cc.png)
没有开启

**Comment by SnowMoonSS** [comment]
系统信息：
版本	Windows 11 专业版
版本	21H2
安装日期	‎2022/‎4/‎23
操作系统版本	22000.708
体验	Windows 功能体验包 1000.22000.708.0

**Comment by Loskh** [comment]
下个版本试着修一下，不一定好使

**Comment by Loskh** [comment]
#9096d3d9284c641627448b721c6a58d9e7d0ae5a

**Comment by Loskh** [comment]
9096d3d9284c641627448b721c6a58d9e7d0ae5a
