### ISSUE TITLE
自启动相关

### ISSUE THREAD

**Issue by Calvaire** [ottercorp/FFXIVQuickLauncher#15]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to FFXIV updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

请问以管理员身份运行和随游戏关闭这两项为什么不能同时选择呢
![Snipaste_2022-06-04_22-01-26](https://user-images.githubusercontent.com/4760425/172004296-619d7de0-dabf-4108-b3b8-6d431ab852ae.png)

### Version

Standard version (Windows, Lutris)

### Platform

Windows

**Comment by Loskh** [comment]
因为XL不是管理员权限，无法关闭管理员权限运行的act
另外国服act和原版有一些改动，所以即使用管理员运行XL，也无法自动关闭act
