### ISSUE TITLE
账户管理器显示错位

### ISSUE THREAD

**Issue by InfSein** [ottercorp/FFXIVQuickLauncher#20]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

Windows 11 家庭中文版 21H2 (22000.675)
打开账户管理器后，窗口固定在右下角，且无法移动
![image](https://user-images.githubusercontent.com/54071139/173581470-6b4fe5e7-68f0-404f-8766-1fc8cec38fad.png)

### 平台

Windows

**Comment by wozaiha** [comment]
这是开了游戏开的账号管理？

**Comment by InfSein** [comment]
是，但是没开游戏的时候也是这样

**Comment by Loskh** [comment]
能否说明一下这个bug怎样才能复现？

**Comment by InfSein** [comment]
测试了一下，账号管理窗口的显示逻辑似乎是在启动器的右下区显示，程序打开时默认的居中位置会导致他显示位置超出屏幕而显示不全。
这可能是因为我的显示屏是高分屏？（笔记本大小的2.5K屏幕）
![image](https://user-images.githubusercontent.com/54071139/174474398-b7685ff3-15b1-447e-9781-745ab357af59.png)
![Uploading image.png…]()
