### ISSUE TITLE
希望能加上本地登陆凭证过期的提醒

### ISSUE THREAD

**Issue by Nana-Sama** [ottercorp/FFXIVQuickLauncher#23]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to FFXIV updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

当本地凭证过期时自动登录会提示叨鱼登录的码，但是叨鱼不打开手机应用时收不到登录请求，此时只能取消登录然后再次点击登录用二维码扫描。
能不能做一个在点击自动登录前就可以提示本地凭证已过期的功能？或者直接弹出二维码以减少取消登录再点击登录的步骤。

### Version

Standard version (Windows, Lutris)

### Platform

Windows

**Comment by Loskh** [comment]
我的正好今天过期，试了一下，会正常返回到登陆页面，你可以上传一下你的日志吗？

**Comment by Nana-Sama** [comment]
![image](https://user-images.githubusercontent.com/8022253/177049066-9a1c7a8e-ed2b-435c-8145-223929255696.png)
操作步骤：
1、选中[快速登录]的情况下点击【登录】按钮
2、显示叨鱼的登录码，等待确认（但是由于叨鱼在未打开的情况下不会提示有登录申请，而且打开叨鱼app之后也不会将正在等待的登录申请显示以滑动登录）
3、取消登录
4、选中[快速登录]的情况下点击【登录】按钮
5、出现二维码，使用叨鱼扫码登录

虽然是叨鱼的问题——关闭app的情况下有登录请求不会有推送，且打开app之后也不会显示登录请求；但是想登录器能不能规避一下这个问题，就像我上面所说——选中[快速登录]的情况下点击【登录】按钮前就可以提示本地凭证已过期，或者如果本地登录凭证是否过期是靠点击【登录】按钮之后才能判断，能否在点击【登录】按钮之后直接显示二维码，因为二维码是可以让用户在显示之后再去打开叨鱼app然后就可以登录的。

**Comment by Loskh** [comment]
![Code_XdVaC6VaMV](https://user-images.githubusercontent.com/22745697/177050227-8108ae1d-0b65-48c1-9eb8-b9fa94cd56af.png)
我是这样的，看起来你那边没有正确判断刀鱼是否在线，确实是刀鱼的问题。

**Comment by Nana-Sama** [comment]
叨鱼那边的问题那就没办法了，不过是不是可以在登录器加一个本地凭证过期的时间提醒？据我所知本地凭证的过期时间是一周，我觉得我这边这个问题从用户操作的角度来说，是由于用户不知道本地凭证已经过期了，所以也没有在发起登录请求的时候提前打开叨鱼APP，所以需要取消登录请求再次请求出二维码才能登录。
如果页面上可以提示本地凭证已经过期的话，用户就可以提前打开叨鱼，无需像我这样进行先取消、然后打开叨鱼、再次点击登录、然后扫二维码登录这样的操作了。
不知道这个建议是否可以考虑一下。

**Comment by wozaiha** [comment]
是否为特定安卓版本用户？
IOS系统目前推送正常（除非手机刀鱼也过期了）

**Comment by Nana-Sama** [comment]
> 是否为特定安卓版本用户？ IOS系统目前推送正常（除非手机刀鱼也过期了）

iOS系统
刚刚确认了一下，是之前没有打开叨鱼通知的原因，打开通知后用官方启动器实验了一下可以在叨鱼未打开的情况下收到登录请求。
非常感谢，是我这边的疏忽，如果带来了困扰很抱歉。
