### ISSUE TITLE
XLCore在Linux平台上登陆二维码叨鱼无法识别

### ISSUE THREAD

**Issue by bamdragonfly** [ottercorp/FFXIVQuickLauncher#27]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

在Linux上启动XLCore进行扫码登陆时，二维码周围白色区域太少，手机叨鱼无法识别二维码。

### 平台

Linux (native)

**Comment by Bluefissure** [comment]
Fixed https://github.com/ottercorp/FFXIVQuickLauncher/commit/0baee61c03faaec6c5176c09f5b1f7eaaecd1943
