### ISSUE TITLE
quick launcher 无法安装国服6.1版本更新

### ISSUE THREAD

**Issue by Orghana** [ottercorp/FFXIVQuickLauncher#31]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

补丁下载一切正常，但结束下载后无法安装补丁，显示“正在更新第0/20个补丁”

![image](https://user-images.githubusercontent.com/49580707/183596466-fe1d7301-9060-4ccf-b5f5-ffe495622503.png)

### 平台

Windows

**Comment by Loskh** [comment]
下班修

**Comment by Loskh** [comment]
fixed,bdd307f61dc0bb9ac8b5da752d0a8a47d0d857a1
