### ISSUE TITLE
xivlauncher在启动之后造成Wegame端登录出现bug

### ISSUE THREAD

**Issue by uiharuayako** [ottercorp/FFXIVQuickLauncher#32]
### 更新免责声明

- [X] #33

### 您做了什么？

我的主要账号是Wegame端的，游戏也是使用Wegame下载和更新的。最近注册了一个盛趣的小号，发现launcher能选择wegame端的游戏文件夹并且正常运行盛趣端的小号（使用快速登陆，叨鱼扫码）。
但是之后再次运行wegame端账号之后报错如下
![bug](https://user-images.githubusercontent.com/52899485/183642625-4c5b6676-d4a5-48ef-b1e8-c9fee375fc6b.png)
点掉窗口之后游戏也无法正常运行。使用Wegame的修复功能检查游戏文件完整性之后，Wegame端账号才能正常运行，这个bug在我电脑上今天出现过两次。
请问xivlauncher登陆过程中会不会造成game文件夹中文件的改动？能不能通过备份这些改动的文件来解决这个问题，毕竟检验游戏完整性挺浪费时间的呜呜

### 平台

Windows

**Comment by Bluefissure** [comment]
如果双端共享客户端请只为game文件夹设置链接
