### ISSUE TITLE
proton experiment installation has failed

### ISSUE THREAD

**Issue by leslielg** [ottercorp/FFXIVQuickLauncher#41]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

steam添加非steam游戏，选择下载的setup.exe,强制使用steam play,版本proton experiment。点击运行
![image](https://user-images.githubusercontent.com/5469646/186458882-73b11383-5e5a-45cf-9091-161cced76a2a.png)

有国服native Linux的版本？没找到呢？

### 平台

Linux (Wine/Proton)

**Comment by Bluefissure** [comment]
Linux可以自行编译 https://github.com/ottercorp/FFXIVQuickLauncher/tree/CN/src/XIVLauncher.Core

**Comment by leslielg** [comment]
不知道怎么build，没看到Makefile之类的。能build一个Ubuntu 22.04用的吗？

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Loskh** [comment]
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build
这样build

**Comment by leslielg** [comment]
FFXIVQuickLauncher/src/XIVLauncher.Core (CN)$ dotnet build
段错误 (核心已转储)

**Comment by leslielg** [comment]
我不是你们项目的开发人员，自己build太耽误时间了，你们也没有准确的build guide。
希望你们能提供Linux native的binary

**Comment by Bluefissure** [comment]
项目开发人员没有 Ubuntu 22.04 环境

**Comment by leslielg** [comment]
这个问题没有解决就close？什么玩意儿

**Comment by Bluefissure** [comment]
> 这个问题没有解决就close？什么玩意儿

xlcore目前在测试阶段，如果有需求请自行编译。

**Comment by leslielg** [comment]
> 

我的需求看1楼，走natvie build是你们建议的。native build这个方法不行就回到前面setup.exe+proton的问题，怎么就close了

**Comment by Bluefissure** [comment]
> 有国服native Linux的版本？

没有，如果希望使用请自行编译。

>我不是你们项目的开发人员，自己build太耽误时间了，你们也没有准确的build guide。

开发人员安装 Ubuntu 更耽误时间。Build guide 请自行搜索学习 dotnet core in Linux。

> 希望你们能提供Linux native的binary

我们没有这种义务，同时我个人不喜欢你的这种伸手的态度。

推荐阅读：[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**Comment by leslielg** [comment]
你没有native build就要回头去解决setup.exe+proton，既然你开了报issue的频道，直接close掉是什么理由？

去补一下基本逻辑教育



获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Bluefissure** [comment]
close 是因为问题已经解决：如果希望使用请自行编译
