### ISSUE TITLE
DalamudCrashHandler.exe - 无法找到入口

### ISSUE THREAD

**Issue by luoway** [ottercorp/FFXIVQuickLauncher#44]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

启动时弹窗报错，不影响功能
![image](https://user-images.githubusercontent.com/12523415/188299169-3ad5d6be-f5a6-4a22-8fe0-1b114438327b.png)

### 平台

Windows

**Comment by Bluefissure** [comment]
https://ottercorp.github.io/faq/xl_troubleshooting#q-how-can-i-fix-crashes-on-startup
