### ISSUE TITLE
Linux下无法检测到游戏

### ISSUE THREAD

**Issue by akasakakona** [ottercorp/FFXIVQuickLauncher#47]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

在Steam Deck的Discover商店里下载了XIVLauncherCN，第一次运行时让我安装游戏，直接关闭了窗口，出现了登陆界面。之后虽然启动成功，但是第二次开启起动器时又会让我安装游戏。这次登陆界面不再出现。

### 平台

Linux (native)

**Comment by Bluefissure** [comment]
国服无法从头下载游戏，请拷贝游戏到steamdeck内并手动指定游戏目录

**Comment by akasakakona** [comment]
> ~~国服无法从头下载游戏，请拷贝游戏到steamdeck内并手动指定游戏目录~~
> 
> 你的安装游戏是指什么

就是一个界面，让我安装Steam的free trial。可是我游戏都拷贝到指定目录里去了

**Comment by Bluefissure** [comment]
> 就是一个界面，让我安装Steam的free trial。可是我游戏都拷贝到指定目录里去了，甚至都成功启动游戏了

参考 [Steam Deck 指南](https://ottercorp.github.io/faq/steamdeck#%E5%AE%89%E8%A3%85)，你需要下载 https://store.steampowered.com/agecheck/app/312060/ 安装到 Steam Deck 的 **内部存储器** 中。

这个和国服游戏无关，可以理解成一个让 steam 识别正在运行的游戏是 FFXIV，并自动应用相关手柄预设的功能。

**Comment by akasakakona** [comment]
> > 就是一个界面，让我安装Steam的free trial。可是我游戏都拷贝到指定目录里去了，甚至都成功启动游戏了
> 
> 
> 
> 参考 [Steam Deck 指南](https://ottercorp.github.io/faq/steamdeck#%E5%AE%89%E8%A3%85)，你需要下载 https://store.steampowered.com/agecheck/app/312060/ 安装到 Steam Deck 的 **内部存储器** 中。
> 
> 
> 
> 这个和国服游戏无关，可以理解成一个让 steam 识别正在运行的游戏是 FFXIV，并自动应用相关手柄预设的功能。

明白了，感谢。是我没有仔细读
