### ISSUE TITLE
使用代理无法启动国服，不使用代理启动国服之后插件库无法更新

### ISSUE THREAD

**Issue by Yellabble** [ottercorp/FFXIVQuickLauncher#49]
### 更新免责声明

- [x] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

使用代理无法启动国服，不使用代理启动国服之后插件库无法更新

### 平台

Windows

**Comment by Bluefissure** [comment]
网络问题，请检查你的代理与网络
