### ISSUE TITLE
Patch补全计划

### ISSUE THREAD

**Issue by Loskh** [ottercorp/FFXIVQuickLauncher#55]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

盛趣在服务器上删除一些2.0的补丁包(4个)，3.0的补丁包（1个），导致XL无法和国际服一样，从零打补丁产生完整游戏，会导致几个文件不完整或缺失。
需要通过完整性校验结果推测这5个patch内容，并使用ZiPatch的AddFile Chunk，将影响到的文件打包成缺失的patch。

### Version

Both

### Platform

Applies to all

**Comment by Bluefissure** [comment]
缺失的补丁包:

game:
http://ff.autopatch.sdo.com/ff/game/c38effbc/D2014.03.24.0000.0000.patch: 404
http://ff.autopatch.sdo.com/ff/game/c38effbc/D2014.03.24.0001.0000.patch: 404
http://ff.autopatch.sdo.com/ff/game/c38effbc/D2014.03.24.0002.0000.patch: 404
http://ff.autopatch.sdo.com/ff/game/c38effbc/D2014.03.24.0003.0000.patch: 404
http://ff.autopatch.sdo.com/ff/game/c38effbc/D2014.03.24.0004.0000.patch: 404
http://ff.autopatch.sdo.com/ff/game/c38effbc/D2014.03.24.0005.0000.patch: 404
http://ff.autopatch.sdo.com/ff/game/c38effbc/D2014.03.24.0006.0000.patch: 404
2014.07.22 大丈夫测试开始
http://ff.autopatch.sdo.com/ff/game/c38effbc/D2014.11.26.0000.0001.patch: 200

ex1:
http://ff.autopatch.sdo.com/ff/game/ex1/77420d17/D2015.09.04.0000.0000.patch: 200
http://ff.autopatch.sdo.com/ff/game/ex1/77420d17/D2015.09.04.0000.0001.patch: 200
http://ff.autopatch.sdo.com/ff/game/ex1/77420d17/D2015.10.26.0000.0001.patch: 404
2015.11.19 3.0上线
http://ff.autopatch.sdo.com/ff/game/ex1/77420d17/D2016.01.20.0000.0001.patch: 200

因此，只需要：
1. 找到大丈夫测试的客户端，使用 Zipatch 模拟一下最开始的几个包
2. 找到 3.0 上线时的客户端，使用空文件夹打入 `D2015.09.04.0000.0000` `D2015.09.04.0000.0001` 两个补丁包，然后和3.0上线时的客户端对比推断出 `D2015.10.26.0000.0001` 的内容

**Comment by Bluefissure** [comment]
sdo修复了ex1的patch问题，目前仅有
://ffautopatchurl/ff/game/c38effbc/D2014.03.24.0000.0000.patch: 404
://ffautopatchurl/ff/game/c38effbc/D2014.03.24.0001.0000.patch: 404
://ffautopatchurl/ff/game/c38effbc/D2014.03.24.0002.0000.patch: 404
://ffautopatchurl/ff/game/c38effbc/D2014.03.24.0003.0000.patch: 404
://ffautopatchurl/ff/game/c38effbc/D2014.03.24.0004.0000.patch: 404
://ffautopatchurl/ff/game/c38effbc/D2014.03.24.0005.0000.patch: 404
://ffautopatchurl/ff/game/c38effbc/D2014.03.24.0006.0000.patch: 404
缺失

找到了 2014.11.05.0000.0000 的客户端，似乎可以模拟一个 patch 出来

**Comment by Bluefissure** [comment]
sdo将7.0之前的补丁全合并图层打包成了History patch，nice work！
