### ISSUE TITLE
在Deck上使用是是否兼容ge-proton或者v社官方的proton？

### ISSUE THREAD

**Issue by chinanoahli** [ottercorp/FFXIVQuickLauncher#56]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

一般来说Deck至少都带有一个proton/wine环境，能否直接使用这个环境，而不是另外下载一个新的wine？

另外QQ频道完全没法用了啊，申请马甲的子频道被删除了，新成员私信管理者也没权限。

### Version

Native/Core version (Linux)

### Platform

Linux (Wine/Proton)

**Comment by Bluefissure** [comment]
xlcore里面可以更改所使用的wine，而且似乎proton对中文字符集的支持更好一些？

**Comment by Bluefissure** [comment]
QQ频道身份申请在阅读完频道公告后
