### ISSUE TITLE
希望可以将需要的组件的下载链接直接放出

### ISSUE THREAD

**Issue by chinanoahli** [ottercorp/FFXIVQuickLauncher#57]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

启动器自动下载的时候，经常因为某些你懂的原因，下载慢，或者干脆下载不了的情况

希望可以简单写一下手册，如何手动安装组件包，例如`FMV cutscens`，我这边不论挂不挂代理都下载得非常慢，还很容易掉线

### Version

Native/Core version (Linux)

### Platform

Linux (Wine/Proton)

**Comment by chinanoahli** [comment]
折腾了半天，发现每次是下载一个完全一样的1.6g，1.9版本的Mac版游戏本体
能否将下载时的文件名指定成同一个……随机文件名导致了就算下载成功，但下一次还是会重新下载
然后每次都重新下1.6G

**Comment by Bluefissure** [comment]
https://file.bluefissure.com/FFXIV/Dalamud/xlcore/deck/gamefix/
