### ISSUE TITLE
允许在Wine/CrossOver中以管理员权限运行安装程序 (Allow installer run as administrator on Wine)

### ISSUE THREAD

**Issue by wdhwg001** [ottercorp/FFXIVQuickLauncher#59]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

我尝试使用CrossOver执行安装程序，发现它提示我不应该以管理员权限打开它，但CrossOver中并未提供不以管理员权限启动的方式。

我当前使用的绕过方法是先在Windows虚拟机下安装，随后将其复制到CrossOver中启动，但这样对于没有虚拟机或者真实Windows的用户颇为不便。

I tried to run the installer with CrossOver 22.0.1.35507, but the installer complained it should not be run as administrator. Unfortunately, running as normal user is currently not an option for CrossOver.

My current workaround is to install it first on a Windows VM (Parallel Desktop), and then copy it back to CrossOver. It's quite inconvenient especially for those who don't have a working Windows environment.

### Version

Standard version (Windows, Lutris)

### Platform

Mac OS X

**Comment by Bluefissure** [comment]
请使用xlcore，.net framework版本的xivlauncher并没有提供wine下的支持

**Comment by chxbca** [comment]
CrossOver 环境可以直接下载 XIVLauncherCN-**-full.nupkg 文件, zip 解压后使用 lib/net45/XIVLauncherCN.exe 启动
