### ISSUE TITLE
创建快捷方式后，双击打开无法自动登录游戏

### ISSUE THREAD

**Issue by NicoOrz** [ottercorp/FFXIVQuickLauncher#6]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

双击快捷方式后，启动启动器与正常打开无区别，无法自动登录

### Platform

Windows

**Comment by wozaiha** [comment]
快捷方式的效果只是复制粘贴用户名及（不存在的）密码
自动登录属于另一部分的内容
国服由于不能游戏内切换服务器
目前自动登录暂时不允许使用
