### ISSUE TITLE
处理"对不起，操作失败，请联系客服95105222"

### ISSUE THREAD

**Issue by Loskh** [ottercorp/FFXIVQuickLauncher#65]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

`
2023-05-27 16:32:20.915 +08:00 [INF] staticLogin.json:ErrorType=0:ReturnCode=-10742003:FailReason:对不起，操作失败，请联系客服95105222:NextAction=2
`
一般在新电脑上第一次登陆账号，可能会出现以上报错，右键登陆按钮，选择扫码登陆，可以正常登陆。
处理方法可选：

1. 报错文本中附加内容，提示用户可以右键登陆，选择扫码。
2. 出现该异常时，自动无感fallback到扫码登陆。

### Version

Standard version (Windows, Lutris)

### Platform

Applies to all

**Comment by wozaiha** [comment]
我记得现在已经自动跳转扫码了？
