### ISSUE TITLE
windows hello support

### ISSUE THREAD

**Issue by FairyScript** [ottercorp/FFXIVQuickLauncher#7]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to FFXIV updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

将缓存的登录信息放置在系统安全区内
自动登录时拉起windows hello验证

理论上其他系统平台也有类似的功能可以实现

虽然这是一个国际服平台也可以考虑的功能,但国际服的验证形式与国服并不相同(例如totp)所以姑且将这个问题放在国服分支下

### Version

Both

### Platform

Applies to all

**Comment by wozaiha** [comment]
建议向上游提出Issue
个人认为没有必要进行二次验证，
1.在不能游戏内切换服务器的情况下，自动登录暂不开放，快速登录≠自动登录
2.不论何时，你的手机叨鱼都应能收到登录通知
3.如果你的设备已经被他人操作，那么你的手机或者其他能拉起windows验证的设备/Pin基本也已经沦陷
综上，我认为没有必要继续增加安全性。
