### ISSUE TITLE
有关卫月启动器和客户端出现5003错误

### ISSUE THREAD

**Issue by IceQueennnn** [ottercorp/FFXIVQuickLauncher#71]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

前天我用卫月启动器启动的，并且下线，途中鸟区掉过一次线。昨天再上号，就提示“账号认证发生了错误  5003”，已排除网络问题和电脑问题。（我上别人的号没问题，别人在其他地方上我的号也上不去）我就在客服发了工单。然后今天上午客服那边回复已经处理好了。我这才能上去。感觉是不是启动器出了什么问题导致盛趣那边以为我没有下线呢？是的话，我要提交哪个日志来帮助解决这个可能的问题呢？我现在不敢用卫月启动器了，先用框架手动注入了

### 平台

Windows

**Comment by Bluefissure** [comment]
官方启动器是否正常？

**Comment by IceQueennnn** [comment]
> 官方启动器是否正常？

不行的，哪个启动器都不行。

**Comment by Bluefissure** [comment]
> > 官方启动器是否正常？
> 
> 不行的，哪个启动器都不行。

那应该是账号问题，联系客服解决比较好。

**Comment by IceQueennnn** [comment]
> > > 官方启动器是否正常？
> > 
> > 
> > 不行的，哪个启动器都不行。
> 
> 那应该是账号问题，联系客服解决比较好。

是的，现在已经解决了，但是我就是在想是不是卫月启动器的问题哈哈哈，我真的吓死了以为被封号了
