### ISSUE TITLE
首次启动过程中提示XIVLauncher可以帮我下载游戏，但如果游戏不存在于本地，启动器会报错。

### ISSUE THREAD

**Issue by yulexun** [ottercorp/FFXIVQuickLauncher#72]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

电脑语言为 English （United States）。
使用Releases中的Setup安装启动器进行首次启动的设置。
在选择游戏文件夹的页面提示 "If you don't have the game installed, you can choose an empty folder and XIVLauncher will install it for you.“
![03c986a706d8e20affff85412fd69320](https://github.com/ottercorp/FFXIVQuickLauncher/assets/74227776/db611835-d015-4b62-8878-72d9e8a4b5a9)

我并没有下载游戏本体，因为我认为XIVLauncher会为我下载。在我输入账号并点击 "Log in" 之后，提示：
![image](https://github.com/ottercorp/FFXIVQuickLauncher/assets/74227776/fbae1d43-5ce1-427a-b3f7-e26bc3bb351f)

点击Yes之后，出现以下报错：
![image](https://github.com/ottercorp/FFXIVQuickLauncher/assets/74227776/54b0e2cc-e0f8-4ccf-8230-8e6f5437dadf)

### 平台

Windows

### 相关日志文件

```shell
Context: Problem
2014.03.24.0000.0000
```

**Comment by Bluefissure** [comment]
国服无法从头安装游戏，因为盛趣删除了2015年之前的补丁包
