### ISSUE TITLE
有代理时登陆报错

### ISSUE THREAD

**Issue by shavadawa** [ottercorp/FFXIVQuickLauncher#76]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

我已经把ip和域名加入直连了  也不是全局模式  但只要qv2接管了系统代理  XIVLauncher就无法登录  不过取消系统代理是正常的  (也没啥影响

![1](https://github.com/ottercorp/FFXIVQuickLauncher/assets/47963779/c8fa0fb6-64ff-45fd-89a1-0edaa8d5065a)
![22](https://github.com/ottercorp/FFXIVQuickLauncher/assets/47963779/f21e8699-24f5-4470-be5c-4ba80732077a)
![34](https://github.com/ottercorp/FFXIVQuickLauncher/assets/47963779/9be0c70c-9fa3-4597-babb-88cdde02b0c6)

### 平台

Windows

**Comment by Loskh** [comment]
这个问题只出现在同时使用v2ray+系统代理的情况。别的代理软件不会这样，建议使用别的代理软件试试。

**Comment by pingmoogle** [comment]
> 这个问题只出现在同时使用v2ray+系统代理的情况。别的代理软件不会这样，建议使用别的代理软件试试。

这确实是一个一直存在的问题，请问有考虑重新打开这个issue吗
