### ISSUE TITLE
登录时显示反复要求检查账户密码的正确性

### ISSUE THREAD

**Issue by Congyi-Wang** [ottercorp/FFXIVQuickLauncher#77]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

我像往常一样在启动加速器后使用FIvlauncher登录了游戏，但是这次等录器返回了这样的消息：

System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 XIVLauncher.Common.Game.Launcher.<GetGuid>d__65.MoveNext() 位置 C:\goatsoft\xl\XIVLauncher.Common\Game\SdoLauncher.cs:行号 228
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 XIVLauncher.Common.Game.Launcher.<OauthLoginSdo>d__55.MoveNext() 位置 C:\goatsoft\xl\XIVLauncher.Common\Game\SdoLauncher.cs:行号 94
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 XIVLauncher.Common.Game.Launcher.<LoginSdo>d__44.MoveNext() 位置 C:\goatsoft\xl\XIVLauncher.Common\Game\SdoLauncher.cs:行号 57
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryLoginToGame>d__25.MoveNext() 位置 D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:行号 477

Version: 6.3.12.0
Git Hash: 6.3.12-beta1-0-gbdf47d5c
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: ChineseSimplified
LauncherLanguage: SimplifiedChinese
Game path: H:\Program Files (x86)\上海数龙科技有限公司\最终幻想XIV

我依照网站的教程删除了一次密码，重新扫描叨鱼进行了等录，但是仍然反回了相同的错误。我又使用了其他人的账号，但是仍然无法解决问题。而使用官方的启动器是可以正常启动的。

### 平台

Windows

### 相关日志文件

```shell
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 XIVLauncher.Common.Game.Launcher.<GetGuid>d__65.MoveNext() 位置 C:\goatsoft\xl\XIVLauncher.Common\Game\SdoLauncher.cs:行号 228
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 XIVLauncher.Common.Game.Launcher.<OauthLoginSdo>d__55.MoveNext() 位置 C:\goatsoft\xl\XIVLauncher.Common\Game\SdoLauncher.cs:行号 94
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 XIVLauncher.Common.Game.Launcher.<LoginSdo>d__44.MoveNext() 位置 C:\goatsoft\xl\XIVLauncher.Common\Game\SdoLauncher.cs:行号 57
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryLoginToGame>d__25.MoveNext() 位置 D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:行号 477

Version: 6.3.12.0
Git Hash: 6.3.12-beta1-0-gbdf47d5c
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: ChineseSimplified
LauncherLanguage: SimplifiedChinese
Game path: H:\Program Files (x86)\上海数龙科技有限公司\最终幻想XIV
```

**Comment by Congyi-Wang** [comment]
我已经尝试使用了管理权权限打开xivlauncher，重新下载使用xivlauncher，但目前无法解决问题。

**Comment by Congyi-Wang** [comment]
甚至在新下载的xivlauncher中使用扫码登录也是弹出一样的错误

**Comment by dypcoder** [comment]
![image](https://github.com/ottercorp/FFXIVQuickLauncher/assets/22155645/f988fd52-8d28-42f7-a996-dd5d3eae02e2)
我debug了源码，我看登陆请求返回了这个，不知道客户端如何抓包看请求携带了什么参数

**Comment by Loskh** [comment]
根据刚刚抓包结果，XL和官方启动器一致，推测盛趣买的腾讯云服务抽风，请使用全局代理/加速器规避抽风的腾讯云节点，或尝试使用官方启动器。

**Comment by Loskh** [comment]
> 据我研究这个插件目前应该G了，getGuid.json 这个接口的参数变成加密的了，不知道加密方法是啥，在大佬解包研究出来之前应该用不了，不太熟悉c#和win编程，说错见谅

可以上传一下你的抓包结果吗？

**Comment by dypcoder** [comment]
![image](https://github.com/ottercorp/FFXIVQuickLauncher/assets/22155645/22811ca9-a853-4f33-a74f-6f99e4b87163)
![image](https://github.com/ottercorp/FFXIVQuickLauncher/assets/22155645/5387e9f5-ee98-4568-8b8b-1e9695935d99)
我看代码应该是不管那种登陆方式都会先从这个接口拿cookie然后在进行登录方式的选择(不知道对不对)
现在这个那cookie的接口加密了，后面那一串key应该是一堆参数的加密后的密文，现在拿不到cookie了，就报错了

**Comment by dypcoder** [comment]
后面的那一串密文会变化，我试了两次，每次都不一样

**Comment by Loskh** [comment]
![image](https://github.com/ottercorp/FFXIVQuickLauncher/assets/22745697/159966c5-46ab-4b5d-b67b-7bd47f76ed7a)
我这边官方启动器抓包结果没有这个，很奇怪

**Comment by zszsj1231234** [comment]
不清楚是不是系统问题我这边Windows端也这样报错，在steam deck端的是可以正常登录的

**Comment by chaosdreams123** [comment]
我windows这边也是这样报错

**Comment by Loskh** [comment]
> 抓包XIVLAUNCHER启动会出现访问访问受限，但是使用浏览器请求同一个url是能正常获取response 猜测是启动器的http请求参数被反爬
> 
> edit: 在尝试稳定复现访问受限的情况下 从https改用http能够正常访问 感觉大概率是https的问题了 edit again: 测出来tls1.2不行 tls1.3 可以 查了一下资料 好像windows10不支持通过SCHANNEL支持tls1.3 https://learn.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-#tls-protocol-version-support

感谢测试，最终发现Tls11可行

**Comment by dypcoder** [comment]
> ~~据我研究这个插件目前应该G了，getGuid.json 这个接口的参数变成加密的了，不知道加密方法是啥，在大佬解包研究出来之前应该用不了，不太熟悉c#和win编程，说错见谅~~
---
确实跟腾讯云抽风有关
 ```html
<!DOCTYPE html><html><meta charset="UTF-8"><meta content="width=device-width,initial-scale=1" name="viewport"><title>AccessDeny</title><style>html{font-size:30px;font-family:PingFangSC-Regular}.content{padding:0 30px 0;width:1200px}.text1{font-size:1.25em}.text2{font-size:.625em}.text3{font-size:.75em;margin:100px 0}.footer-line{border-top:1px solid #000}</style><body style="display:none"><div class="content"><h1 class="err">Restricted Access</h1><p class="text2"><span id="id1">Request ID:</span><span>7573785009569928485</span></p><p class="text3">The security policy of this website has blocked you from further access.</p><div class="footer-line"><p class="text2"><span id="id3">Protected by Tencent Cloud EdgeOne</span></p></div></div></body><script>function changeLang(){["zh-cn","zh"].includes((navigator.userLanguage||navigator.language).toLowerCase())&&(document.querySelector(".err").innerHTML="访问受限",document.querySelector(".text3").innerHTML="您的请求已被该站点的安全策略拦截。",document.querySelector("#id1").innerHTML="请求 ID：",document.querySelector("#id3").innerHTML="由 Tencent Cloud EdgeOne 提供防护"),document.body.style="display: block"}changeLang()</script></html>
 ```
win10 tls1.1亲测可行，确实与tls有关

**Comment by Arc10p** [comment]
> 新版本已推送 [6.3.12-beta2](https://github.com/ottercorp/FFXIVQuickLauncher/releases/tag/6.3.12-beta2) 请尝试是否还存在问题

已能正常使用

**Comment by Frosnowxd** [comment]
> > 新版本已推送 [6.3.12-beta2](https://github.com/ottercorp/FFXIVQuickLauncher/releases/tag/6.3.12-beta2) 请尝试是否还存在问题
> 
> 已能正常使用

已经正常了
