### ISSUE TITLE
无法登陆？

### ISSUE THREAD

**Issue by k99k5** [ottercorp/FFXIVQuickLauncher#9]
### Update disclaimer

- [x] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

System.AggregateException: 发生一个或多个错误。 ---> System.ComponentModel.Win32Exception: 'CredWrite' call throw an error (Error code: 1312)
   在 AdysTech.CredentialManager.CredentialManager.SaveCredentials(String target, NetworkCredential credential)
   在 XIVLauncher.Windows.ViewModel.MainWindowViewModel.PersistAccount(String username, String password)
   在 XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__25.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass24_0.<TryLogin>b__1()
---> (内部异常 #0) System.ComponentModel.Win32Exception (0x80004005): 'CredWrite' call throw an error (Error code: 1312)
   在 AdysTech.CredentialManager.CredentialManager.SaveCredentials(String target, NetworkCredential credential)
   在 XIVLauncher.Windows.ViewModel.MainWindowViewModel.PersistAccount(String username, String password)
   在 XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__25.MoveNext()<---

Version: 6.2.36.0
Git Hash: 6.2.36-0-g3fcb687-dirty
Context: GetLoginFunc/Task
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: ChineseSimplified
LauncherLanguage: SimplifiedChinese
Game path: G:\FF14\最终幻想XIV

### Platform

Windows

**Comment by Bluefissure** [comment]
参考 https://github.com/goatcorp/FFXIVQuickLauncher/issues/587

**Comment by k99k5** [comment]
> 参考 [goatcorp#587](https://github.com/goatcorp/FFXIVQuickLauncher/issues/587)

貌似还是不行，win11上把凭据删掉了 账户也删掉了，然后launcher已经需要重新输入账号了 但是重新输入登陆后还是同样的报错

**Comment by Bluefissure** [comment]
可能需要更新一个依赖库，可以等待下个版本

**Comment by k99k5** [comment]
> 可能需要更新一个依赖库，可以等待下个版本

刚更新了alpha1 但是还是不行）

**Comment by Bluefissure** [comment]
> > 可能需要更新一个依赖库，可以等待下个版本
> 
> 刚更新了alpha1 但是还是不行）

能附上最新的错误日志吗？

**Comment by Bluefissure** [comment]
> > > > 可能需要更新一个依赖库，可以等待下个版本
> > > 
> > > 
> > > 刚更新了alpha1 但是还是不行）
> > 
> > 
> > 能附上最新的错误日志吗？
> 
> 和之前的一样的 不过我测试了一下没有管理员权限的情况下没问题，只要一给权限就这样了

怪，那暂时先别用管理员运行吧，alpha1应该不需求管理员权限了。
