### ISSUE TITLE
这些软件将随游戏启动。功能有异常

### ISSUE THREAD

**Issue by WSMTBG** [ottercorp/FFXIVQuickLauncher#90]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

![图片](https://github.com/ottercorp/FFXIVQuickLauncher/assets/32087250/22349431-1ac0-4d65-b9cf-e2cb9baca770)
无法关闭随游戏启动的ACT

### 平台

Windows

**Comment by WSMTBG** [comment]
![图片](https://github.com/ottercorp/FFXIVQuickLauncher/assets/32087250/0c3890a9-c16e-4791-bef9-bc93e7c4c7cd)
卫月也是给了管理员权限的

**Comment by Bluefissure** [comment]
点我启动ACT是ACT的启动器，自然不会关闭ACT

**Comment by WSMTBG** [comment]
> 点我启动ACT是ACT的启动器，自然不会关闭ACT

诶原来是这样的吗，谢谢

**Comment by WSMTBG** [comment]
> 点我启动ACT是ACT的启动器，自然不会关闭ACT

![图片](https://github.com/ottercorp/FFXIVQuickLauncher/assets/32087250/c6591459-6fae-4f0c-8ad0-486b2d2c96fb)
我填了ACT本体（这个是本体吧）还是不行

**Comment by Bluefissure** [comment]
似乎此处只是随游戏启动，你需要的是随游戏关闭？

**Comment by WSMTBG** [comment]
> ~似乎此处只是随游戏启动，你需要的是随游戏关闭？~ OK，有时间测试一下

是的，不知道是我act有问题还是电脑问题，游戏关闭后一段时间act会占用很高，还经常会忘记关act...

**Comment by wozaiha** [comment]
国服的cafe和呆萌似乎打了一些奇怪的补丁，呆萌曾经提过最好不要用除了手工关闭以外的方式尝试关闭ACT（参考STP特供的ACT自启动功能）

**Comment by WSMTBG** [comment]
> 国服的呆萌似乎打了一些奇怪的补丁，呆萌曾经提过最好不要用除了手工关闭以外的方式尝试关闭ACT（参考STP特供的ACT自启动功能）

啊这，那ffcafe那个ACT可以吗

**Comment by wozaiha** [comment]
我没有问过cafe那边，你可以自行尝试

**Comment by LittleNightmare** [comment]
我昨天试了下启动（结果我启动不来，overlay的配置文件还炸了（还好有备份

**Comment by WSMTBG** [comment]
> 我没有问过cafe那边，你可以自行尝试

试了，管理员启动的卫月可以随游戏关闭cafe

**Comment by wozaiha** [comment]
> > 我没有问过cafe那边，你可以自行尝试
> 
> 
> 
> 试了，管理员启动的卫月可以随游戏关闭cafe

那就先用cafe吧，议题我先关了？

**Comment by WSMTBG** [comment]
> > > 我没有问过cafe那边，你可以自行尝试
> > 
> > 
> > 试了，管理员启动的卫月可以随游戏关闭cafe
> 
> 那就先用cafe吧，议题我先关了？

okk
