### ISSUE TITLE
卫月插件不生效/输入法会导致崩溃

### ISSUE THREAD

**Issue by jasonzou1** [ottercorp/FFXIVQuickLauncher#91]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

启动卫月插件后使用中文输入法按任何字母键都会导致游戏立即崩溃，用英文输入法进入游戏后无法使用游戏内的任何卫月插件功能并且一切换中文输入法打字就会崩溃。

### 平台

Windows

### 相关日志文件

```shell
Unhandled native exception occurred at KERNELBASE.dll+5FABC	(RaiseException+0x6C)
Code: C0000005
Dump at: D:\weiyue\XIVLauncherCN\Roaming\addon\Hooks\9.1.0.2\..\..\..\..\Roaming\dalamud_appcrash_20240717_222458_207_23204.dmp
System Time: 2024-07-17 14:24:59.9477530

   at ImGuiNET.ImGuiIOPtr.get_WantTextInput()
   at Dalamud.Game.Gui.GameGui.HandleImmDetour(IntPtr framework, Char a2, Byte a3)


Exception Info #0
Address: C0000005
Flags: 80
Address: 7FF7E2AF4F90
Parameters: 0, 8
Call Stack
{
  [0]	KERNELBASE.dll+5FABC	(RaiseException+0x6C)
  [1]	KERNELBASE.dll+5FABC	(RaiseException+0x6C)
  [2]	coreclr.dll+21C842	(GetCLRRuntimeHost+0xA6E2)
  [3]	coreclr.dll+1B3926	(coreclr_set_error_writer+0x5AF46)
  [4]	ntdll.dll+77F5A	(RtlGetLengthWithoutLastFullDosOrNtPathElement+0x3DA)
  [5]	ntdll.dll+1E642	(RtlFindCharInUnicodeString+0x872)
  [6]	ntdll.dll+A403E	(KiUserExceptionDispatcher+0x2E)
  [7]	7FF7E2AF4F90
  [8]	53AF9AF5D0
  [9]	8
  [10]	BD1BAB0EBB8
  [11]	53AF9AF4F8
  [12]	B
  [13]	8
  [14]	53AF9AF5E0
  [15]	7FF7E2AF4E14
  [16]	53AF9AF5D0
  [17]	8
  [18]	BD1BAB0EBB8
  [19]	53AF9AF4F8
  [20]	192A3D14748
  [21]	192A3D13060
  [22]	8
  [23]	100000000
  [24]	53AF9AF650
  [25]	7FF7E2AF4D11
  [26]	192A3979C88
  [27]	19289737D80
  [28]	1
  [29]	52
  [30]	53AF9AF5F0
}

Registers
{
  RAX:	clrjit.dll+17E748	(getLikelyMethods+0x2D328)
  RBX:	53AF9AF330 [C0000005]
  RCX:	1D3ECFEB038
  RDX:	clrjit.dll+183078	(jitBuildString+0x47F8)
  R8:	7FF800000057
  R9:	clrjit.dll+F12E0 [4810588948C48B48]
  R10:	clrjit.dll+17E728	(getLikelyMethods+0x2D308)
  R11:	1D3ECFEB038
  R12:	1929F516860 [1929D4A8F60]
  R13:	53AFBF8000 [4000000]
  R14:	7E
  R15:	0
  RSI:	53AF9B0000
  RDI:	53AF9AEB90 [53AF9AF330]
  RBP:	53AF9B0000
  RSP:	53AF9AE4A0 [7FF7E2AF4F70]
  RIP:	KERNELBASE.dll+5FABC	(RaiseException+0x6C)
}

Stack
{
  [RSP+0]	7FF7E2AF4F70 [6C8D4830EC834855]
  [RSP+8]	53AF9AF330 [C0000005]
  [RSP+10]	53AF9B0000
  [RSP+18]	coreclr.dll+218628	(GetCLRRuntimeHost+0x64C8)
  [RSP+20]	80C0000005
  [RSP+28]	0
  [RSP+30]	7FF7E2AF4F90 [548F8458B480038]
  [RSP+38]	7FF700000002
  [RSP+40]	0
  [RSP+48]	8
  [RSP+50]	192820CB140 [1929F571550]
  [RSP+58]	886E1749160
  [RSP+60]	1929D4715F0 [coreclr.dll+3C9008	(coreclr_shutdown+0x139A8)]
  [RSP+68]	7FF7E1748BF0 [2800040000BBA4]
  [RSP+70]	7FF7E2AF4FC0 [104D8948EC8B4855]
  [RSP+78]	1929F531460 [19284AE7630]
}

Modules
{
  00400000	C:\WINDOWS\SYSTEM32\XInput1_3.dll	Microsoft Common Controller API v9.18.944.0
  10000000	D:\SogouInput\14.6.0.9734\Resource.dll
```

**Comment by wozaiha** [comment]
建议换成QQ输入法试试

**Comment by jasonzou1** [comment]
已解决，是gshade的问题。使用gshade第三种兼容方式重新安装以后不让卫月修复兼容性问题就不会崩溃，卫月跳提示修复了兼容性的话就会导致游戏崩溃。。。希望可以修复下这个问题。

**Comment by Bluefissure** [comment]
> 已解决，是gshade的问题。使用gshade第三种兼容方式重新安装以后不让卫月修复兼容性问题就不会崩溃，卫月跳提示修复了兼容性的话就会导致游戏崩溃。。。希望可以修复下这个问题。

GShade 版本是？

**Comment by jasonzou1** [comment]
> > 已解决，是gshade的问题。使用gshade第三种兼容方式重新安装以后不让卫月修复兼容性问题就不会崩溃，卫月跳提示修复了兼容性的话就会导致游戏崩溃。。。希望可以修复下这个问题。
> 
> GShade 版本是？

5.1.0版本（使用gshadepanel安装的官网最新版），并且使用directinput Mode的hooking模式安装就没有问题

**Comment by Bluefissure** [comment]
能否发送一份`dalamud.log`?

**Comment by jasonzou1** [comment]
> 能否发送一份`dalamud.log`?

[dalamud.log](https://github.com/user-attachments/files/16269333/dalamud.log)
我重现了一下错误，另一个电脑的log我看了没有相关内容

**Comment by jasonzou1** [comment]
> > > 能否发送一份`dalamud.log`?
> > 
> > 
> > [dalamud.log](https://github.com/user-attachments/files/16269333/dalamud.log) 我重现了一下错误，另一个电脑的log我看了没有相关内容
> 
> 这个是报错的log还是没有问题的log？
> 
> ```
> 2024-07-17 11:12:28.830 -04:00 [INF] ReShade DLL: E:\ff\ff14cn\最终幻想XIV\game\dxgi.dll with DXGISwapChain::runtime_present at 7FFEB4D19185
> ```
> 
> 显示成功找到了 ReShade 的 dll
[dalamud.log](https://github.com/user-attachments/files/16269546/dalamud.log)
看看这份，我又重现了一下，这一份就是安装Gshade后使用卫月自带兼容性修复后crash的log

**Comment by Bluefissure** [comment]
你是否有尝试 https://aonyx.ffxiv.wang/faq/dalamud_troubleshooting#q-reshade-%E5%8F%8A%E5%85%B6%E5%8F%98%E4%BD%93%E4%B8%8D%E8%B5%B7%E4%BD%9C%E7%94%A8%E6%88%96-dalamud-ui-%E5%A4%B1%E8%B4%A5 ？

**Comment by jasonzou1** [comment]
> 你是否有尝试 https://aonyx.ffxiv.wang/faq/dalamud_troubleshooting#q-reshade-%E5%8F%8A%E5%85%B6%E5%8F%98%E4%BD%93%E4%B8%8D%E8%B5%B7%E4%BD%9C%E7%94%A8%E6%88%96-dalamud-ui-%E5%A4%B1%E8%B4%A5 ？

使用卫月自带的兼容性修复会自动把这个文件改名，如果改名的话就会导致游戏崩溃，维持原来的文件名游戏就可以正常运行并且Gshade和卫月都可以启动

**Comment by Bluefissure** [comment]
https://github.com/goatcorp/Dalamud/issues/1836

**Comment by jasonzou1** [comment]
> [goatcorp/Dalamud#1836](https://github.com/goatcorp/Dalamud/issues/1836)

是这个一样的问题，但是目前只会出现在国服版的卫月，国际服版本的卫月已经没有这个问题了。国服版本已经确认通过改变gshade的hook方式以及维持文件名不作修改可以修复。
