### ISSUE TITLE
登陆器 密码登陆问题

### ISSUE THREAD

**Issue by shavadawa** [ottercorp/FFXIVQuickLauncher#92]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

用登陆器登录之前登陆过的账号会弹出扫码 点开密码框存在密码  **且用官方登陆器密码登陆成功**  也就是说密码登陆是正常的 那为什么会弹出扫码呢

### 平台

Windows

**Comment by Bluefissure** [comment]
密码登陆失败时会自动切换成扫码登陆
