### ISSUE TITLE
常规版本会自动更新到测试版本

### ISSUE THREAD

**Issue by banshee-attack** [ottercorp/FFXIVQuickLauncher#95]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

老版本更新会更新到测试版本导致无法启动游戏
![image](https://github.com/user-attachments/assets/49b304c2-b6e1-4abf-a708-154d7738bb08)

### 平台

Windows

**Comment by wozaiha** [comment]
beta3依旧无法启动吗?请发送报错截图或文件

**Comment by WSMTBG** [comment]
> beta3依旧无法启动吗?请发送报错截图或文件

System.InvalidOperationException: Assertion failure.
   在 XIVLauncher.Windows.CustomMessageBox.AssertOrShowError(Boolean condition, String context, Boolean fatal, Window parentWindow) 位置 D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\CustomMessageBox.xaml.cs:行号 491

Version: 6.4.1.0
Git Hash: 6.4.1-beta3-0-g54212f00
Context: TryProcessLoginResult: loginResult.State should have been Launcher.LoginState.Ok
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: ChineseSimplified
LauncherLanguage: SimplifiedChinese
Game path: E:\最终幻想XIV

**Comment by wozaiha** [comment]
请尝试重新扫码登录
