### ISSUE TITLE
linux无法正常登陆提示登陆过程被取消

### ISSUE THREAD

**Issue by zszsj1231234** [ottercorp/FFXIVQuickLauncher#96]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

就正常登陆马上提示登陆过程被取消

### 平台

Linux (native)

**Comment by Loskh** [comment]
https://github.com/ottercorp/XIVLauncher.Core Linux用这个

**Comment by zszsj1231234** [comment]
> https://github.com/ottercorp/XIVLauncher.Core Linux用这个

好的我试试
