### ISSUE TITLE
linux下通过faq里的教程通过steam设置XLM兼容层运行闪退

### ISSUE THREAD

**Issue by zszsj1231234** [ottercorp/FFXIVQuickLauncher#99]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

按照faq设置好兼容层后，在steam版ff14更改兼容层打开提示运行马上就steam显示游戏退出。

### 平台

Linux (Wine/Proton)

### Wine/Proton 运行版本

XLM

**Comment by Bluefissure** [comment]
你是否有对ff14修改启动参数？

**Comment by zszsj1231234** [comment]
> Bluefissure

没有，重新安装xlm有一段看着像是报错的样子，日志如下：
(deck@steamfork ~)$ sh -c "$(curl -fsSL https://file.bluefissure.com/d/FFXIV/Dalamud/xlcore/xlm/install-native-cn.sh)"
-- XLM Native 自动安装脚本(CN) --

[Step: 1] 下载 XLM
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.5M  100 11.5M    0     0  6559k      0  0:00:01  0:00:01 --:--:-- 6560k
[Step: 2] 配置 XLM 作为 Steam 兼容工具
01:01:43 [INFO] Setting up the XLM compatibility tool inside of "/tmp/steam-compat/XLM"
01:01:43 [INFO] Extra launch args: Some("--xlm-updater-disable --xlcore-web-release-url-base=\"https://s3.otters.cloud/xlcore/distrib/\""), Extra env vars: None
01:01:43 [INFO] Successfully set up compatibility tool please restart steam for it to correctly appear.
[Step: 3] 重命名兼容工具 XLM -> XLM_CN
[Step: 4] 清理 XLM 二进制文件

-- 自动安装程序完成：返回游戏模式并按照 README 文件继续！ --

里面的https://s3.otters.cloud/xlcore/distrib/手动访问显示为证书到期不清楚时不时这个问题

**Comment by Bluefissure** [comment]
> > Bluefissure
> 
> 没有，重新安装xlm有一段看着像是报错的样子，日志如下： (deck@steamfork ~)$ sh -c "$(curl -fsSL https://file.bluefissure.com/d/FFXIV/Dalamud/xlcore/xlm/install-native-cn.sh)" -- XLM Native 自动安装脚本(CN) --
> 
> [Step: 1] 下载 XLM % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 100 11.5M 100 11.5M 0 0 6559k 0 0:00:01 0:00:01 --:--:-- 6560k [Step: 2] 配置 XLM 作为 Steam 兼容工具 01:01:43 [INFO] Setting up the XLM compatibility tool inside of "/tmp/steam-compat/XLM" 01:01:43 [INFO] Extra launch args: Some("--xlm-updater-disable --xlcore-web-release-url-base="[https://s3.otters.cloud/xlcore/distrib/\](https://s3.otters.cloud/xlcore/distrib/%5C)""), Extra env vars: None 01:01:43 [INFO] Successfully set up compatibility tool please restart steam for it to correctly appear. [Step: 3] 重命名兼容工具 XLM -> XLM_CN [Step: 4] 清理 XLM 二进制文件
> 
> -- 自动安装程序完成：返回游戏模式并按照 README 文件继续！ --
> 
> 里面的[https://s3.otters.cloud/xlcore/distrib/手动访问显示为证书到期不清楚时不时这个问题](https://s3.otters.cloud/xlcore/distrib/%E6%89%8B%E5%8A%A8%E8%AE%BF%E9%97%AE%E6%98%BE%E7%A4%BA%E4%B8%BA%E8%AF%81%E4%B9%A6%E5%88%B0%E6%9C%9F%E4%B8%8D%E6%B8%85%E6%A5%9A%E6%97%B6%E4%B8%8D%E6%97%B6%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98)

域名写错了，应该是 `s3.ffxiv.wang`，已经修正，重新运行脚本即可。

**Comment by zszsj1231234** [comment]
> > > Bluefissure
> > 
> > 没有，重新安装xlm有一段看着像是报错的样子，日志如下： (deck@steamfork ~)$ sh -c "$(curl -fsSL https://file.bluefissure.com/d/FFXIV/Dalamud/xlcore/xlm/install-native-cn.sh)" -- XLM Native 自动安装脚本(CN) --
> > 
> > [Step: 1] 下载 XLM % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 100 11.5M 100 11.5M 0 0 6559k 0 0:00:01 0:00:01 --:--:-- 6560k [Step: 2] 配置 XLM 作为 Steam 兼容工具 01:01:43 [INFO] Setting up the XLM compatibility tool inside of "/tmp/steam-compat/XLM" 01:01:43 [INFO] Extra launch args: Some("--xlm-updater-disable --xlcore-web-release-url-base="[https://s3.otters.cloud/xlcore/distrib/\](https://s3.otters.cloud/xlcore/distrib/%5C)""), Extra env vars: None 01:01:43 [INFO] Successfully set up compatibility tool please restart steam for it to correctly appear. [Step: 3] 重命名兼容工具 XLM -> XLM_CN [Step: 4] 清理 XLM 二进制文件
> > 
> > -- 自动安装程序完成：返回游戏模式并按照 README 文件继续！ --
> > 
> > 里面的[https://s3.otters.cloud/xlcore/distrib/手动访问显示为证书到期不清楚时不时这个问题](https://s3.otters.cloud/xlcore/distrib/%E6%89%8B%E5%8A%A8%E8%AE%BF%E9%97%AE%E6%98%BE%E7%A4%BA%E4%B8%BA%E8%AF%81%E4%B9%A6%E5%88%B0%E6%9C%9F%E4%B8%8D%E6%B8%85%E6%A5%9A%E6%97%B6%E4%B8%8D%E6%97%B6%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98)
> 
> 域名写错了，应该是 `s3.ffxiv.wang`，已经修正，重新运行脚本即可。

好的我在尝试看看

**Comment by lattaai5** [comment]
Hello, I tried to fix the issue

This is what I did:

Modify the UnixGameRunner class to handle Steam-specific launching requirements. This change adds a check for the Steam environment and modifies the launch process accordingly.

I also created pull request: https://github.com/ottercorp/FFXIVQuickLauncher/pull/100


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by zszsj1231234** [comment]
> > > Bluefissure
> > 
> > 
> > 没有，重新安装xlm有一段看着像是报错的样子，日志如下： (deck@steamfork ~)$ sh -c "$(curl -fsSL https://file.bluefissure.com/d/FFXIV/Dalamud/xlcore/xlm/install-native-cn.sh)" -- XLM Native 自动安装脚本(CN) --
> > [Step: 1] 下载 XLM % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 100 11.5M 100 11.5M 0 0 6559k 0 0:00:01 0:00:01 --:--:-- 6560k [Step: 2] 配置 XLM 作为 Steam 兼容工具 01:01:43 [INFO] Setting up the XLM compatibility tool inside of "/tmp/steam-compat/XLM" 01:01:43 [INFO] Extra launch args: Some("--xlm-updater-disable --xlcore-web-release-url-base="[https://s3.otters.cloud/xlcore/distrib/](https://s3.otters.cloud/xlcore/distrib/%5C)""), Extra env vars: None 01:01:43 [INFO] Successfully set up compatibility tool please restart steam for it to correctly appear. [Step: 3] 重命名兼容工具 XLM -> XLM_CN [Step: 4] 清理 XLM 二进制文件
> > -- 自动安装程序完成：返回游戏模式并按照 README 文件继续！ --
> > 里面的[https://s3.otters.cloud/xlcore/distrib/手动访问显示为证书到期不清楚时不时这个问题](https://s3.otters.cloud/xlcore/distrib/%E6%89%8B%E5%8A%A8%E8%AE%BF%E9%97%AE%E6%98%BE%E7%A4%BA%E4%B8%BA%E8%AF%81%E4%B9%A6%E5%88%B0%E6%9C%9F%E4%B8%8D%E6%B8%85%E6%A5%9A%E6%97%B6%E4%B8%8D%E6%97%B6%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98)
> 
> 域名写错了，应该是 `s3.ffxiv.wang`，已经修正，重新运行脚本即可。

已经可以
